parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     null
    database_name:     symfony
    database_user:     root
    database_password: null

    mailer_transport:  gmail
    mailer_host:       ~
    mailer_user:       fatbotmedia@gmail.com
    mailer_password:   fatbotmedia2014
    mailer_encryption: ssl
    mailer_auth_mode: login

    locale:            fr
    secret:            ThisTokenIsNotSoSecretChangeIt